#pragma once // 중복include 방지

#include <sys/types.h>  // basic type definitions
#include <sys/socket.h> // socket(), AF_INET, ...
#include <arpa/inet.h>  // htons(), htonl(), ...
#include <netdb.h>      // gethostbyname(), ...
#include <unistd.h>     // close(), ...
#include <fcntl.h>      // fcntl(), ...
#include <pthread.h>    // pthread_create(), ...
#include <poll.h>       // poll()
#include <sys/epoll.h>  // epoll()

#include <stdio.h>  // printf(), ...
#include <stdlib.h> // exit(), ...
#include <string.h> // strerror(), ...
#include <errno.h>  // errno

// Windows 소켓 코드와 호환성을 위한 정의
typedef int SOCKET;
#define SOCKET_ERROR -1
#define INVALID_SOCKET -1

// 공통 에러 처리 함수
void err_quit(const char *msg);    // 소켓 함수 오류 출력 후 종료
void err_display(const char *msg); // 소켓 함수 오류 출력
void err_display(int errcode);     // 소켓 함수 오류 출력 (오류 코드로)

void SetNonBlocking(SOCKET sock); // 소켓을 넌블로킹 모드로 설정